<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class FormExampleRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required|min:2|max:30',
            'age' => 'required|numeric|min:18'
        ];
    }

    public function messages(): array
    {
        parent::messages(); // TODO: Change the autogenerated stub
        $messages = [
            'name.required' => 'du lieu bat buoc',
            'name.min' => 'can nhap nhieu hon 2 ki tu',
            'name.max' => 'can nhap it hon 30 ki tu',
            'age.required' => 'du lieu bat buoc',
            'age.numeric' => 'du lieu phai la dang so',
            'age.min' => 'du lieu phai co nho nhat la 18'
        ];
        return $messages;
    }
}
